- name: copy Mongodb repo file
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
    
- name: Install mongodb
  yum:
    name: mongodb-org
    state: present
    
- name: start & enable MongoDB service
  system:
    name: mongod
    state: started
    enabled: yes
    