- name: Create an EC2 Instance
  hosts: all
  become: yes
  tasks:
    - name: install pip3
      yum:
        name: python3-pip
        state: present

    - name: install pip
      yum:
        name: python-pip
        state: present

    - name: Install boto
      pip:
        name: boto

    - name: Create an ec2 server
      ec2:
        key_name: Nvkey
        instance_type: t2.micro
        image: ami-0affd4508a5d2481b

