- name: Create an EC2 Instance
  hosts: all
  become: yes
  tasks:
    - name: install pip3 for dependency
      yum:
        name: python3-pip
        state: present

    - name: install pip for dependency
      yum:
        name: python-pip
        state: present

    - name: Install boto for dependency
      pip:
        name: boto

    - name: Create an ec2 server
      ec2:
   #    exact_count: 1
        key_name: Nvkey
        instance_type: t2.micro
        image: ami-0affd4508a5d2481b
        region: us-east-1
        wait: true
        group_id: sg-08eee104cf5e5f8fd
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"

- name: Update new instance
  hosts: launched
  become: True
  gather_facts: True
  tasks:
    - name: Install pre packages
      shell: yum update
    - name: Install wget
      shell: yum install wget
    - name: download epel repo
      shell: wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - name: Install epel repo
      shell: yum install epel-release-latest-7.noarch.rpm
    - name: Install pre packages
      shell: yum update

- name: run roboshop frontend
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - frontend

#    - name: Terminate instances
#      hosts: localhost
#      tasks:
#        - name: Terminate instances that were previously launched
#          amazon.aws.ec2:
#            state: 'absent'
#            instance_ids: '{{ ec2.instance_ids }}'

