- name: Create an EC2 Instance
  hosts: all
  become: yes
  tasks:
    - name: install pip3 for dependency
      yum:
        name: python3-pip
        state: present

    - name: install pip for dependency
      yum:
        name: python-pip
        state: present

    - name: Install boto for dependency
      pip:
        name: boto

    - name: Create an ec2 server
      ec2:
   #    exact_count: 1
        key_name: Nvkey
        instance_type: t2.micro
        image: ami-0affd4508a5d2481b
        region: us-east-1

