- name: Setup roboshop project
  hosts: all
  become: yes
#  roles: IN roles rerunning all tasks so we are going with tag concept
#    - mongodb
#    - redis
  tasks:
    - name: Run mongoDB
      import_role:
        name: mongodb
      tags: [mangodb]

    - name: Run redis
      import_role:
        name: redis
      tags: [redis]

    - name: Run mysql
      import_role:
        name: mysql
      tags: [mysql]
