- name: Setup roboshop project
  hosts: all
  become: yes
#  roles: IN roles rerunning all tasks so we are going with tag concept
#    - mongodb
#    - redis
  tasks:
    - name: Run mongoDB
      import_role:
        name: mongodb
      tags: [mangodb]

    - name: Run redis
      import_role:
        name: redis
      tags: [redis]

    - name: Run mysql
      import_role:
        name: mysql
      tags: [mysql]

    - name: Run rabbitmq
      import_role:
        name: rabbitmq
      tags: [rabbitmq]

    - name: Run cart
      import_role:
        name: cart
      tags: [cart]

    - name: Run catalogue
      import_role:
        name: catalogue
      tags: [catalogue]

    - name: Run user
      import_role:
        name: user
      tags: [user]

    - name: Run shipping
      import_role:
        name: shipping
      tags: [shipping]
