- name: Install Erlang is a dependency for RabbitMQ
  yum:
    name: https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_23.2.1-1~centos~7_amd64.rpm
    state: present

- name: Setup YUM repositories for RabbitMQ
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install RabbitMQ
  yum:
    name: rabbitmq-server
    state: present

- name: start RabbitMQ service
  systemd:
    name: rabbitmq-server
    enabled: yes
    state: started


