- name: Install MySQL
  include_role:
    name: mysql
    tasks_from: install

- name: download schema mysql
  include_role:
    name: common
    tasks_from: download-packages-from-git.yml

- name: Unarchive mysql
  unarchive:
    src: /tmp/ansible-project/{{APP_NAME}}.tar
    dest: /tmp
    remote_src: yes

#- name: Unarchive mysql
#  unarchive:
#    src: /tmp/ansible-project/ratings.tar
#    dest: /tmp
#    remote_src: yes
#
#- name: Unarchive mysql
#  unarchive:
#    src: /tmp/ansible-project/shippings.tar
#    dest: /tmp
#    remote_src: yes
- name: Install GCC
  yum:
    name: "{{item}}"
    state: present
  loop:
    - gcc
    - python-devel

- name: Install pip
  pip:
    name: MySQL-python

- name: Load Schema
  mysql_db:
    state: import
    name: all
    target: "{{item}}"
 #   login_user: root
 #   login_password: "dJYk&%*!K!"
  loop:
    - /tmp/ratings.sql
    - /tmp/shipping.sql

#  mysql_user:
#    login_user: root
#    login_password: dJYk&%*!K
#    host: all
#    name: root
#    password: dJYk&%*!K

