- name: Install rating depenencies
  yum:
    name: "{{item}}"
    state: present
  loop:
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    - httpd

- name: Install PHP
  yum:
    name: "{{item}}"
    state: present
    enablerepo: remi-php73
  loop:
    - php
    - php-opcache
    - php73-php-pdo
    - composer



