- name: Install pip
  yum:
    name: python3-pip
#    update_cache: yes
    state: present

- name: Install boto3
  pip:
    name: boto3
- name: Install boto3 and botocore with pip3 module
  pip:
    name:
      - boto3
      - botocore
    executable: pip


- name: download package
  aws_s3:
    bucket: "{{S3_BUCKET}}"
    object: "{{APP_NAME}}.zip"
    dest: "/tmp/{{APP_NAME}}.zip"
    mode: get
