- name: install python2-pip
  yum:
    name: python2-pip
    state: present

- name: Upgrade pip
  pip: name=pip
  state: latest
  tags:
    - packages

- name: Install pip
  yum:
    name: python-pip
    update_cache: yes
    state: present

- name: Install boto3
  pip:
    name: boto3

- name: download package
  aws_s3:
    bucket: "{{S3_BUCKET}}"
    object: "{{APP_NAME}}.zip"
    dest: "/tmp/{{APP_NAME}}.zip"
    mode: get
